# Generated by Django 5.2.17 on 2026-08-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('industry', models.CharField(max_length=100)),
                ('minimum_experience', models.IntegerField(default=0, help_text='Minimum experience years required')),
                ('description', models.TextField(blank=True, null=True)),
                ('embedding', models.TextField(blank=True, help_text='SBERT 384d embedding serialized as JSON array', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('raw_text', models.TextField(help_text='Full pasted job description text')),
                ('extracted_skills', models.JSONField(blank=True, default=dict, help_text='JSON dictionary of extracted skills {skill_name: matched_text}')),
                ('embedding', models.TextField(blank=True, help_text='SBERT 384d embedding serialized as JSON array', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
                ('job_role', models.ForeignKey(blank=True, help_text='Reference predefined job role if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobrole')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('semantic_score', models.FloatField(default=0.0)),
                ('skill_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('education_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('certification_score', models.FloatField(default=0.0)),
                ('explanation', models.TextField(blank=True, help_text='Natural language explanation of suitability and gaps', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jobs.jobdescription')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='True if required, False if preferred/optional')),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='resumes.skill')),
            ],
            options={
                'unique_together': {('job_role', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('missing', 'Missing'), ('partial', 'Partially Matched'), ('recommended', 'Recommended')], max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Why this skill is relevant and how to acquire it', null=True)),
                ('analysis_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='jobs.analysisresult')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_gaps', to='resumes.skill')),
            ],
            options={
                'unique_together': {('analysis_result', 'skill')},
            },
        ),
    ]
